path/circle_yaw:
  ros__parameters:
    freq: 30
    wz: 0.3

path/depth_sine:
  ros__parameters:
    freq: 30.0
    amplitude: 0.2
    period: 20.0
    offset: -0.3
    start_from: 0.1
    delay: 0.0
    upper_limit: 0.3
    lower_limit: -1.0

eyes:
  ros__parameters:
    capture_frequency: 10.0

reflex:
  ros__parameters:
    service_names: 
      - '/record'
      - '/attitude/reset_ctrl'
      - '/depth/reset_ctrl'
      - '/input/start_and_stop'
      - '/fatigue'
      - '/path/depth_toggle'
      - '/path/yaw_toggle'

memory:
  ros__parameters:
    topics:
      - '/command:std_msgs/msg/Int32MultiArray'
      - '/input/A_d:std_msgs/msg/Float32' 
      - '/input/alpha_d:std_msgs/msg/Float32'
      - '/input/theta_m:std_msgs/msg/Float32'
      - '/imu/data:sensor_msgs/msg/Imu'
      - '/gps_data:sensor_msgs/msg/NavSatFix'
      - '/ms5837/pose:geometry_msgs/msg/PoseWithCovarianceStamped'
      - '/est/odom:nav_msgs/msg/Odometry'
      - '/attitude/w_ref:geometry_msgs/msg/Vector3'
      - '/attitude/q_ref:geometry_msgs/msg/PoseStamped'
      - '/attitude/roll_set:std_msgs/msg/Float32'
      - '/attitude/pitch_set:std_msgs/msg/Float32'
      - '/attitude/yaw_set:std_msgs/msg/Float32'
      - '/depth/z_set:std_msgs/msg/Float32'
    parent_folder: 'bags/circle_path'

fatigue:
  ros__parameters:
    time_out: 120.0
