
command_test_node:
  ros__parameters:
    delay: 5.0
    commands:
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,0.0,0.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,40.0,0.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,-40.0,0.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,0.0,40.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,0.0,-40.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,30.0,30.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,-30.0,30.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,30.0,-30.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,40.0,20.0"
      - "60.0,0.0,0.0,0.0,0.0,0.0:60.0,0.0,0.0,0.0,20.0,40.0"
#      - "30.0,0.0,0.0,0.0,0.0,0.0:30.0,0.0,0.0,0.0,-40.0,20.0"
#      - "30.0,0.0,0.0,0.0,0.0,0.0:30.0,0.0,0.0,0.0,-20.0,40.0"
#      - "30.0,0.0,0.0,0.0,0.0,0.0:30.0,0.0,0.0,0.0,40.0,-20.0"
#      - "30.0,0.0,0.0,0.0,0.0,0.0:30.0,0.0,0.0,0.0,20.0,-40.0"



ctrl:
  ros__parameters:
    freq: 30
    angle_range: [-60, 60]
    pwm_range: [19500, 43500]
    start_wing: [1.0, 0.0, 0.0, 0.0] # | omega_m | A_m | A_d | alpha_d |
    start_flap: [0.0, 0.0]           # | theta_m | theta_d |
    clamp_flap: [-40, 40]

eyes:
  ros__parameters:
    capture_frequency: 10.0

reflex:
  ros__parameters:
    service_names: 
      - '/record'
      - '/input/start_and_stop'
      - '/on_and_off'
      - '/fatigue'
      - '/path/circle_reset'
    

memory:
  ros__parameters:
    topics:
      - '/button_state:std_msgs/msg/Bool'
      - '/command:std_msgs/msg/Int32MultiArray'
      - '/omega_m:std_msgs/msg/Float32'
      - '/A_m:std_msgs/msg/Float32'
      - '/A_d:std_msgs/msg/Float32'
      - '/alpha_d:std_msgs/msg/Float32'
      - '/alpha_m:std_msgs/msg/Float32'
      - '/theta_m:std_msgs/msg/Float32'
      - '/theta_d:std_msgs/msg/Float32'
      - '/imu/data:sensor_msgs/msg/Imu'
      - '/gps_data:sensor_msgs/msg/NavSatFix'
      - '/ms5837/pose:geometry_msgs/msg/PoseWithCovarianceStamped'
      - '/odom:nav_msgs/msg/Odometry'
      - '/camera_1:sensor_msgs/msg/Image'
      - '/camera_2:sensor_msgs/msg/Image'
    parent_folder: 'bags/control_test'

fatigue:
  ros__parameters:
    time_out: 20.0
